version: '3.6'

services:
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  mediaconverter:
    build:
      context: .
      target: dev
    depends_on:
      - "rabbitmq"
    tty: true
    stdin_open: true
    environment:
      - BROKER=amqp://user:password@rabbitmq:5672/
    command:
      bash -c "sleep 15 && /venv/bin/celery -A main worker --concurrency=1"
    volumes:
      - .:/code
