[tool.poetry]
name = "mediaconverter"
version = "0.1.0"
description = ""
authors = ["Kevin Yokley <kyokley2@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"
qtfaststart = "^1.8"
scapy = "^2.4.3"
unidecode = "^1.1.1"
celery = "^4.4.6"
flask = "^1.1.2"
uwsgi = "^2.0.19"

[tool.poetry.dev-dependencies]
mock = "^4.0.2"
nose = "^1.3.7"
bandit = "^1.6.2"
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
